inherits:
  - strictness_veryhigh

uses:
    - django
    - celery

ignore-patterns:
  - ^setup.py$
  - wsgi.py$
  - ^static

pylint:
  disable:
    - missing-final-newline
    - too-few-public-methods
    - too-many-ancestors
    - W0613
    - W0704
    - W0142

  options:
    max-locals: 25
    max-returns: 6
    max-branches: 20
    max-statements: 60
    min-public-methods: 1
    max-public-methods: 20
    max-line-length: 120
    max-args: 10
    max-module-lines: 1200

pep8:
  options:
    max-line-length: 120
  disable:
    - W292
    - W391
    - E402

pyroma:
  disable:
    - PYR15
    - PYR18
    - PYR17

pep257:
  run: true
  disable:
    - D100
    - D101
    - D104
    - D202
    - D203

mccabe:
  options:
    max-complexity: 20

dodgy:
  run: false