name: Test Semgrep Rules

on:
  push:
  pull_request:

env:
  TAG: semgrep-tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        load: true
        tags: ${{ env.TAG }}
    - name: Test obrigatory rules
      run: docker run $TAG

  test_todo:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        load: true
        tags: ${{ env.TAG }}
    - name: Test all rules, including `todo` rules
      run: docker run $TAG --quiet --test --no-test-ignore-todo .